name: This Is A Website
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5925201731733978
title: THIS IS THE WEBSITE TITLE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#d0e0ed'
    - '#443123'
    - '#dbb48b'
    - '#ac733c'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
